-- CORE relational backend
-- Applied to fresh Supabase project: xtagvyyopokrhvvnseom
--
-- Migration name:
--   20260601000000_upgrade_scheduler_to_relational_auth_backend
--
-- The live migration replaces the temporary scheduler_state review document
-- with the conference-room scheduler backend pattern:
--
--   auth.users
--     -> public.profiles
--     -> public.account_requests
--
--   public.organizations
--   public.categories
--   public.reservations
--   public.blocked_times
--   public.announcements
--   public.concerns
--   public.activity_logs
--
-- Browser clients use these RPCs:
--
--   public.create_scheduler_account(...)
--   public.apply_account_request_decision(...)
--   public.get_scheduler_store()
--   public.save_scheduler_store(jsonb)
--
-- Public viewers can call get_scheduler_store() without an account. New
-- accounts are created in Supabase Auth with pending profiles. Only an active
-- super-admin can approve access requests. Authenticated save calls are
-- checked against active profile role and organization membership.
--
-- The authoritative SQL is stored in the Supabase migration history for
-- project xtagvyyopokrhvvnseom. Do not apply this backend to the original
-- conference-room scheduler project.
